<?xml version="1.0" encoding="UTF-8" ?>
<!-- This WordPress eXtended RSS file is  generated by WP Export -->
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="WordPress/{WP-VERSION}" created="{FULL-DATE-TIME}" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>
    <channel>
		<!-- General informations -->
    	<title>{SITE-TITLE}</title>
        <link>{SITE-URL}</link>
        <description>{SITE-DESCRIPTION}</description>
        <pubDate>{SITE-PUBLISH-DATE}</pubDate>
        <language>{SITE-LANGUAGE}</language>
        <wp:wxr_version>1.2</wp:wxr_version>
        <wp:base_site_url>{SITE-URL}</wp:base_site_url>
        <wp:base_blog_url>{SITE-URL}</wp:base_blog_url>
		<!-- Author informations -->
{LOOP-AUTHOR}		<wp:author><wp:author_id>{AUTHOR-ID}</wp:author_id><wp:author_email>{AUTHOR-EMAIL}</wp:author_email><wp:author_display_name><![CDATA[{AUTHOR-DISPLAY-NAME}]]></wp:author_display_name><wp:author_first_name><wp:author_last_name><![CDATA[{AUTHOR-LAST-NAME}]]></wp:author_last_name></wp:author>
{/LOOP-AUTHOR}
		<!-- Categories -->
{LOOP-CATEGORY-TERM}		<wp:category><wp:term_id>{TERM-ID}</wp:term_id><wp:category_nicename>{TERM-SLUG}</wp:category_nicename><wp:category_parent>{TERM-PARENT}</wp:category_parent><wp:cat_name><![CDATA[{TERM-NAME}]]></wp:cat_name><wp:category_description><![CDATA[{TERM-DESCRIPTION}]]></wp:category_description></wp:category>
{/LOOP-CATEGORY-TERM}
		<!-- Tags -->
{LOOP-TAG}		<wp:tag><wp:term_id>{TERM-ID}</wp:term_id><wp:term_idname>{TERM-ID}</wp:term_idname><wp:tag_slug>{TERM-SLUG}</wp:tag_slug><wp:tag_name><![CDATA[{TERM-NAME}]]></wp:tag_name><wp:tag_description><![CDATA[{TERM-DESCRIPTION}]]></wp:tag_description></wp:tag>
{/LOOP-TAG}
		<!-- Custom taxonomy -->
{LOOP-TERM}		<wp:term><wp:term_id>{TERM-ID}</wp:term_id><wp:term_idname>{TERM-ID}</wp:term_idname><wp:tag_slug>{TERM-SLUG}</wp:tag_slug><wp:tag_name><![CDATA[{TERM-NAME}]]></wp:tag_name><wp:tag_description><![CDATA[{TERM-DESCRIPTION}]]></wp:tag_description></wp:term>
{/LOOP-TERM}
		<!-- Post and pages -->
{LOOP-ITEM}		<item>
			<title>{ITEM-TITLE}</title>
			<link>{ITEM-LINK}</link>
			<pubDate>{ITEM-DATE-PUBLISH}</pubDate>
			<dc:creator><![CDATA[{ITEM-AUTHOR}]]></dc:creator>
			<guid isPermaLink="false">{ITEM-PERMIT-LINK}</guid>
			<description>{ITEM-DESCRIPTION}</description>
			<content:encoded><![CDATA[{ITEM-CONTENT}]]></content:encoded>
			<excerpt:encoded><![CDATA[{ITEM-EXCERPT}]]></excerpt:encoded>
			<wp:post_id>{ITEM-ID}</wp:post_id>
			<wp:post_date>{ITEM-DATE-EDIT}</wp:post_date>
			<wp:post_date_gmt>{ITEM-DATE-ADD}</wp:post_date_gmt>
			<wp:comment_status>{ITEM-COMMENT-STATUS}</wp:comment_status>
			<wp:ping_status>{ITEM-PING-STATUS}</wp:ping_status>
			<wp:post_name>{ITEM-SLUG}</wp:post_name>
			<wp:status>{ITEM-STATUS}</wp:status>
			<wp:post_parent>{ITEM-PARENT}</wp:post_parent>
			<wp:menu_order>{ITEM-ORDER}</wp:menu_order>
			<wp:post_type>{ITEM-TYPE}</wp:post_type>
			<wp:post_password>{ITEM-PASSWORD}</wp:post_password>
			<wp:is_sticky>{ITEM-STICKY}</wp:is_sticky>
			<wp:attachment_url>{ITEM-ATTACHMENT-URL}</wp:attachment_url>
{LOOP-CATEGORY}			<category domain="{CATEGORY-TAXONOMY}" nicename="{CATEGORY-SLUG}"><![CDATA[{CATEGORY-NAME}]]></category>
{/LOOP-CATEGORY}
{LOOP-POSTMETA}			<wp:postmeta>
				<wp:meta_key>{POSTMETA-KEY}</wp:meta_key>
				<wp:meta_value><![CDATA[{POSTMETA-VALUE}]]></wp:meta_value>
			</wp:postmeta>
{/LOOP-POSTMETA}
		</item>
{/LOOP-ITEM}
		<generator>https://wordpress.org/?v={WP-VERSION}</generator>
    </channel>
</rss>